### ISSUE TITLE
Add a new product

### ISSUE THREAD

**Issue by anitaschiller** [ThomasKirst/christmas-factory#2]
## Value Statement
As a vendor I want to be able to add a new product in order to access a product list at a later stage.

## Description
.....
![christmas-factory-form (1)](https://user-images.githubusercontent.com/77627311/148200760-de5282c2-46e1-4aed-9e3d-2df1392f2cc7.png)

## Complexity
L 

## Acceptance Criteria
- The user will be notified if one of the form fields is required and not yet filled
- The user can save his/her product when clicking on the save button
- The user will be notified if one saving the product was successful
- The user should get an offer how to proceed
- The user can empty the input fields when clicking on the cancel button
- The user should not be able to submit the form if fields are not correctly filled

## Tasks
- [ ] Open a new branch
- [x] Create a general component folder
- [x] Create a component for the product form
- [ ] Make form to a controlled component
- [ ] Save the new product in a products useState
- [ ] Add tests

**Comment by anitaschiller** [comment]
## Value Statement
As a vendor I want to be able to add a new product in order to access a product list at a later stage.

## Description
.....
![christmas-factory-form (1)](https://user-images.githubusercontent.com/77627311/148200760-de5282c2-46e1-4aed-9e3d-2df1392f2cc7.png)

## Complexity
L 

## Acceptance Criteria
- [ ] The user will be notified if one of the form fields is required and not yet filled
- [ ] The user can save his/her product when clicking on the save button
- [ ] The user will be notified if one saving the product was successful
- [ ] The user should get an offer how to proceed
- [ ] The user can empty the input fields when clicking on the cancel button
- [ ] The user should not be able to submit the form if fields are not correctly filled

## Tasks
- [ ] Open a new branch
- [ ] Create a general component folder
- [ ] Create a component for the product form
- [ ] Make form to a controlled component
- [ ] Save the new product in a products useState
- [ ] Add tests
